name: Android CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Setup Gradle Wrapper
      run: |
        # Create a new wrapper if needed
        if [ ! -f ./gradlew ]; then
          echo "Creating new Gradle wrapper"
          gradle wrapper --gradle-version 8.2 || true
        fi
        # Make sure gradlew is executable
        chmod +x gradlew
      
    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
      
    - name: Install required SDK components
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      
    - name: Create Debug Keystore
      run: |
        keytool -genkey -v -keystore app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
        
    - name: Build debug APK
      run: |
        # Check if the wrapper is properly set up
        echo "Checking Gradle wrapper files:"
        ls -la
        ls -la gradle/wrapper/
        
        # Verify the wrapper jar exists
        if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
          echo "Gradle wrapper JAR missing, downloading it"
          mkdir -p gradle/wrapper
          curl -o gradle/wrapper/gradle-wrapper.jar https://repo.maven.apache.org/maven2/org/gradle/gradle-wrapper/8.2/gradle-wrapper-8.2.jar
        fi
        
        # Verify the wrapper properties file
        if [ ! -f gradle/wrapper/gradle-wrapper.properties ]; then
          echo "Gradle wrapper properties missing, creating it"
          mkdir -p gradle/wrapper
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
        fi
        
        # Try to build
        ./gradlew --version
        ./gradlew assembleDebug --stacktrace --info
      
    - name: Build release APK
      run: ./gradlew assembleRelease --stacktrace
      
    - name: Run lint checks
      run: ./gradlew lint
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest --continue
      
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
        
    - name: Upload lint reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-reports
        path: app/build/reports/lint-results-*.html
        
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: app/build/reports/tests/
        
    - name: Build summary
      if: always()
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "### APK Files Generated:" >> $GITHUB_STEP_SUMMARY
        echo "- Debug APK: $(ls -lh app/build/outputs/apk/debug/app-debug.apk 2>/dev/null || echo 'Not found')" >> $GITHUB_STEP_SUMMARY
        echo "- Release APK: $(ls -lh app/build/outputs/apk/release/app-release-unsigned.apk 2>/dev/null || echo 'Not found')" >> $GITHUB_STEP_SUMMARY
        echo "### Build Configuration:" >> $GITHUB_STEP_SUMMARY
        echo "- Java Version: $(java -version 2>&1 | head -1)" >> $GITHUB_STEP_SUMMARY
        echo "- Gradle Version: $(./gradlew --version | grep Gradle)" >> $GITHUB_STEP_SUMMARY
        echo "- Android SDK: $ANDROID_HOME" >> $GITHUB_STEP_SUMMARY

  release:
    needs: build
    runs-on: ubuntu-latest
    # Run on main branch push or manual workflow dispatch
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download release APK
      uses: actions/download-artifact@v4
      with:
        name: release-apk
        path: ./
        
    - name: Set up JDK 17 for signing
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Sign APK
      run: |
        # Create a keystore for signing
        keytool -genkey -v -keystore release.keystore -storepass android -alias androidreleasekey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=BudgetWise Release,O=BudgetWise,C=US"
        
        # Sign the APK
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore release.keystore -storepass android -keypass android app-release.apk androidreleasekey
        
        # Verify the signature
        jarsigner -verify -verbose -certs app-release.apk
        
    - name: Get version from gradle
      id: get_version
      run: |
        # Extract base version from defaultConfig (without build type suffixes)
        VERSION=$(grep -A 10 "defaultConfig" app/build.gradle | grep "versionName" | cut -d'"' -f2)
        if [ -z "$VERSION" ]; then
          echo "Error: Could not extract version from build.gradle"
          exit 1
        fi
        
        # For workflow_dispatch events, add timestamp to ensure unique tag
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          VERSION="${VERSION}-${TIMESTAMP}"
          TAG="v${VERSION}"
          TAG_EXISTS="false"
          echo "Creating timestamped version for manual workflow: $VERSION"
        else
          TAG="v${VERSION}"
          # Check if tag exists
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, will create timestamped version"
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            VERSION="${VERSION}-${TIMESTAMP}"
            TAG="v${VERSION}"
            TAG_EXISTS="false"
          else
            TAG_EXISTS="false"
          fi
        fi
        
        echo "Extracted version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "tag_exists=$TAG_EXISTS" >> $GITHUB_OUTPUT
        
    - name: Create Release
      id: create_release
      if: steps.get_version.outputs.tag_exists == 'false'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        name: BudgetWise ${{ steps.get_version.outputs.version }}
        body: |
          ## BudgetWise ${{ steps.get_version.outputs.version }}
          
          ### What's New
          - Personal finance management app
          - Transaction tracking and categorization
          - Budget management with analytics
          - Secure data encryption (AES-256)
          - Biometric authentication support
          - Material 3 design
          - Fixed app crashes on Vivo V23 and similar devices
          - Enhanced error handling and stability improvements
          
          ### Installation
          1. Download the APK file below
          2. Enable "Install from unknown sources" in your Android settings
          3. Install the APK file
          
          ### Technical Details
          - **Minimum Android Version**: Android 7.0 (API 24)
          - **Target Android Version**: Android 14 (API 34)
          - **APK Size**: ~3.1MB (optimized with ProGuard)
          - **Permissions**: Storage, Notifications, Biometric
          
          ### Security
          - All financial data is encrypted using AES-256
          - Biometric authentication for app access
          - No data is transmitted to external servers
        draft: false
        prerelease: false
        files: |
          ./release/app-release.apk
          ./debug/app-debug.apk